# Plugins laden
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark' # oder 'light'

# TPM initialisieren (muss ganz am Ende stehen!)
run '~/.tmux/plugins/tpm/tpm'
